# Generated by Django 6.0.2 on 2026-02-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cca_activities',
            field=models.ManyToManyField(blank=True, related_name='students', to='payments.ccaactivity'),
        ),
    ]
