# Generated by Django 6.0.2 on 2026-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_cca_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bus_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
