# Generated by Django 6.0.2 on 2026-02-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_bus_number_student_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fees',
            new_name='bus_fee',
        ),
        migrations.AddField(
            model_name='student',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
