# Generated by Django 6.0.2 on 2026-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_fees_student_bus_fee_student_tuition_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starting_month',
            field=models.CharField(default='April', max_length=20),
        ),
    ]
