# Generated by Django 6.0.2 on 2026-03-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_starting_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(db_index=True, default='2024-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('admission_no', 'academic_year')},
        ),
    ]
