# Generated by Django 6.0.2 on 2026-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_academic_year_alter_student_admission_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cca_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
