# Generated by Django 6.0.2 on 2026-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_cca_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='starting_year',
            field=models.IntegerField(default=2024),
        ),
    ]
