# Generated by Django 6.0.2 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_academicyear_schoolclass_studentacademicrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_year']},
        ),
        migrations.AddField(
            model_name='academicyear',
            name='end_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='start_year',
            field=models.IntegerField(db_index=True, default=2024),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(default='2025-03-31'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(default='2024-04-01'),
        ),
    ]
