# Generated by Django 6.0.2 on 2026-02-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
