# Generated by Django 6.0.2 on 2026-03-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_receipt_receipt_no'),
        ('students', '0004_rename_fees_student_bus_fee_student_tuition_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='month',
        ),
        migrations.AddField(
            model_name='receipt',
            name='academic_year',
            field=models.CharField(default='2024-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='MonthlyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.feecategory')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.feecategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_mappings', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'fee_category', 'month', 'academic_year')},
            },
        ),
    ]
