# Generated by Django 6.0.2 on 2026-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeemapping',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
