# Generated by Django 6.0.2 on 2026-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_studentfeemapping_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccaactivity',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
