# Generated by Django 6.0.2 on 2026-03-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_receipt_deleted_at_receipt_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycollection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='academic_year',
            field=models.CharField(db_index=True, default='2024-25', max_length=10),
        ),
        migrations.AddField(
            model_name='monthlycollection',
            name='academic_year',
            field=models.CharField(db_index=True, default='2024-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailycollection',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailycollection',
            unique_together={('date', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlycollection',
            unique_together={('month', 'year', 'academic_year')},
        ),
    ]
