# Generated by Django 6.0.2 on 2026-03-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_monthlycollection_unique_together_and_more'),
        ('students', '0009_academicyear_schoolclass_studentacademicrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycollection',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='monthlycollection',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
        migrations.AddField(
            model_name='studentfeemapping',
            name='academic_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_mappings', to='students.studentacademicrecord'),
        ),
        migrations.AddField(
            model_name='studentfeemapping',
            name='academic_year_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.academicyear'),
        ),
    ]
